### ISSUE TITLE
Unit test operator precedence

### ISSUE THREAD

**Issue by dionyziz** [dionyziz/llama#38]

**Comment by Renelvon** [comment]
I will have a final look on the current precedence tests and close this issue if everything is alright.

**Comment by Renelvon** [comment]
The tests are somewhat incomplete and a bit inconsistent:
- Missing test that `+` and `-` have same precedence as `+.` and `-.`.
- `+.` is tested against `\.` while `+` isn't tested against `\`. Similarly for `-.` and `*.` vs `-` and `*`.
- Missing test that comparison and assignment are non-associative operators (i.e. `a == b == c` fails to parse, while `(a == b) == c` parses successfully).
- Since `&&` has higher precedence than `||`, only `&&` needs to be tested against comparison operators. Similarly, assignment needs to be tested only against `||`.
- Since comparison operators are non-associative, it is impossible to verify via testing that they all have the same precedence. So, to have complete test coverage, we should test all comparison operators against `+`.
